In [52]:
# Imports 

import pandas as pd 
import numpy as np
from sqlalchemy import create_engine

In [2]:
# Reading the Nashville data 
nash_data = pd.read_csv("listings.csv")
nash_data.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6422,https://www.airbnb.com/rooms/6422,20211217003604,2021-12-17,Nashville Charm,30 day or more rental during COVID. Show COVID...,Historic East Nashville is home to many new an...,https://a0.muscache.com/pictures/pro_photo_too...,12172,https://www.airbnb.com/users/show/12172,...,4.96,4.92,4.98,NaN,f,1,0,1,0,4.38
1,39870,https://www.airbnb.com/rooms/39870,20211217003604,2021-12-17,Close to Vanderbilt 2,This is a room and private bathroom in my cozy...,"The house is in a safe, quiet, ""college"" neig...",https://a0.muscache.com/pictures/43420407-69b6...,171184,https://www.airbnb.com/users/show/171184,...,4.98,4.94,4.94,NaN,f,1,0,1,0,4.17
2,72906,https://www.airbnb.com/rooms/72906,20211217003604,2021-12-17,Vandy/Belmont/10 mins to Broadway - Sunny 800 ...,Entire top floor. Private. 800 sq ft of bright...,Historic Belmont-Hillsboro neighborhood. Walk-...,https://a0.muscache.com/pictures/58602855/3788...,176117,https://www.airbnb.com/users/show/176117,...,4.99,4.96,4.88,NaN,f,1,1,0,0,4.74
3,258817,https://www.airbnb.com/rooms/258817,20211217003604,2021-12-17,ButterflyRoom-private bath- open in oct,Morningstar House! Extended stay - 3+ months- ...,"I'm very near the Percy Priest Lake, natural ...",https://a0.muscache.com/pictures/eef19bc4-2743...,22296,https://www.airbnb.com/users/show/22296,...,4.90,4.74,4.73,NaN,f,7,0,6,1,0.79
4,289242,https://www.airbnb.com/rooms/289242,20211217003604,2021-12-17,"MorningstarHouse, monthly room- open sept",Morningstar House! Extended stay - price reduc...,The Morningstar House is in a quiet cul-de-sac...,https://a0.muscache.com/pictures/40a7ab72-20f7...,22296,https://www.airbnb.com/users/show/22296,...,4.78,4.47,4.69,NaN,f,7,0,6,1,0.63

In [3]:
#  Nashville data shape
nash_data.shape

(6360, 74)

In [4]:
# Reading the Asheville data 
ashe_data = pd.read_csv("Asheville_listings.csv")
ashe_data.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,108061,https://www.airbnb.com/rooms/108061,20211215062309,2021-12-15,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/41011975/0cdf...,320564,https://www.airbnb.com/users/show/320564,...,4.79,4.84,4.48,NaN,f,2,2,0,0,0.71
1,155305,https://www.airbnb.com/rooms/155305,20211215062309,2021-12-15,Cottage! BonPaul + Sharky's Hostel,<b>The space</b><br />Private cottage located ...,"We are within easy walk of pubs, breweries, mu...",https://a0.muscache.com/pictures/8880711/cf38d...,746673,https://www.airbnb.com/users/show/746673,...,4.76,4.93,4.53,NaN,t,7,1,2,4,2.75
2,156805,https://www.airbnb.com/rooms/156805,20211215062309,2021-12-15,"Private Room ""Ader"" at BPS Hostel",<b>The space</b><br />Private Rooms at Bon Pau...,"Easy walk to pubs, cafes, bakery, breweries, l...",https://a0.muscache.com/pictures/23447d55-fa7e...,746673,https://www.airbnb.com/users/show/746673,...,4.61,4.84,4.46,NaN,t,7,1,2,4,0.54
3,156926,https://www.airbnb.com/rooms/156926,20211215062309,2021-12-15,"Mixed Dorm ""Top Bunk #1"" at BPS Hostel",This is a top bunk in the mixed dorm room<br /...,NaN,https://a0.muscache.com/pictures/98f4e655-c4d6...,746673,https://www.airbnb.com/users/show/746673,...,4.80,4.78,4.78,NaN,t,7,1,2,4,2.36
4,160594,https://www.airbnb.com/rooms/160594,20211215062309,2021-12-15,Historic Grove Park,Come enjoy the beautiful Grove Park neighborho...,NaN,https://a0.muscache.com/pictures/92433837/d340...,769252,https://www.airbnb.com/users/show/769252,...,4.88,4.90,4.85,NaN,f,1,0,1,0,0.46

In [5]:
# Asheville data shape
ashe_data.shape

(2626, 74)

In [6]:
# Checking for duplicates 
nash_unique = nash_data.drop_duplicates(subset=['id'])
nash_unique.shape 
# all unique entries 

ashe_unique = ashe_data.drop_duplicates(subset=['id'])
ashe_unique.shape
# all unique entries

(2626, 74)

In [7]:
nash_unique

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6422,https://www.airbnb.com/rooms/6422,20211217003604,2021-12-17,Nashville Charm,30 day or more rental during COVID. Show COVID...,Historic East Nashville is home to many new an...,https://a0.muscache.com/pictures/pro_photo_too...,12172,https://www.airbnb.com/users/show/12172,...,4.96,4.92,4.98,NaN,f,1,0,1,0,4.38
1,39870,https://www.airbnb.com/rooms/39870,20211217003604,2021-12-17,Close to Vanderbilt 2,This is a room and private bathroom in my cozy...,"The house is in a safe, quiet, ""college"" neig...",https://a0.muscache.com/pictures/43420407-69b6...,171184,https://www.airbnb.com/users/show/171184,...,4.98,4.94,4.94,NaN,f,1,0,1,0,4.17
2,72906,https://www.airbnb.com/rooms/72906,20211217003604,2021-12-17,Vandy/Belmont/10 mins to Broadway - Sunny 800 ...,Entire top floor. Private. 800 sq ft of bright...,Historic Belmont-Hillsboro neighborhood. Walk-...,https://a0.muscache.com/pictures/58602855/3788...,176117,https://www.airbnb.com/users/show/176117,...,4.99,4.96,4.88,NaN,f,1,1,0,0,4.74
3,258817,https://www.airbnb.com/rooms/258817,20211217003604,2021-12-17,ButterflyRoom-private bath- open in oct,Morningstar House! Extended stay - 3+ months- ...,"I'm very near the Percy Priest Lake, natural ...",https://a0.muscache.com/pictures/eef19bc4-2743...,22296,https://www.airbnb.com/users/show/22296,...,4.90,4.74,4.73,NaN,f,7,0,6,1,0.79
4,289242,https://www.airbnb.com/rooms/289242,20211217003604,2021-12-17,"MorningstarHouse, monthly room- open sept",Morningstar House! Extended stay - price reduc...,The Morningstar House is in a quiet cul-de-sac...,https://a0.muscache.com/pictures/40a7ab72-20f7...,22296,https://www.airbnb.com/users/show/22296,...,4.78,4.47,4.69,NaN,f,7,0,6,1,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6355,53848373,https://www.airbnb.com/rooms/53848373,20211217003604,2021-12-17,TWO LUXURY TOWNHOMES - SLEEPS 24,"2 home combo in MidTown now available, located...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,20772148,https://www.airbnb.com/users/show/20772148,...,NaN,NaN,NaN,NaN,t,37,37,0,0,NaN
6356,53849579,https://www.airbnb.com/rooms/53849579,20211217003604,2021-12-17,NYE Buffett Style! Margaritaville Studio Sleeps 4,A prime location in the heart of downtown Nash...,NaN,https://a0.muscache.com/pictures/39e84b36-7480...,372514865,https://www.airbnb.com/users/show/372514865,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
6357,53850709,https://www.airbnb.com/rooms/53850709,20211217003604,2021-12-17,"Good as Gold Rowhouse - Minutes to downtown, V...","Love food, music, rooftop decks and uber comfy...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,26211861,https://www.airbnb.com/users/show/26211861,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
6358,53855857,https://www.airbnb.com/rooms/53855857,20211217003604,2021-12-17,New Year's Eve!! Margaritaville Studio Sleeps 4,This resort offers studio rooms that comfortab...,NaN,https://a0.muscache.com/pictures/39e84b36-7480...,372514865,https://www.airbnb.com/users/show/372514865,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
6359,53859326,https://www.airbnb.com/rooms/53859326,20211217003604,2021-12-17,Nashville Famous - Luxurious Townhome with Swe...,A luxurious and uniquely styled townhome with ...,"Located 6 miles from downtown Nashville, 6 mil...",https://a0.muscache.com/pictures/prohost-api/H...,85360355,https://www.airbnb.com/users/show/85360355,...,NaN,NaN,NaN,NaN,f,81,81,0,0,NaN

In [8]:
# Looking at the columns to drop 
nash_unique.columns

# get ridding of scrape_id, last_scraped, host_has_profile_pic, picture_url, host_thumbnail_url, host_picture_url, host_ neighborhood, bathrooms, neighbourhood_group_cleansed, calendar_updated, minimum_minimum_nights, maximum_minimum_nights, 
# minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm  , maximum_nights_avg_ntm, has_availability, "calendar_last_scraped", "license", "month", 
nash_columns = nash_unique.drop(["scrape_id", "last_scraped", "host_has_profile_pic", "picture_url", "host_thumbnail_url", "host_picture_url", "host_neighbourhood", "bathrooms",\
     "neighbourhood_group_cleansed", "calendar_updated", "minimum_minimum_nights", "maximum_minimum_nights", "minimum_maximum_nights", "maximum_maximum_nights",\
    "minimum_nights_avg_ntm", "maximum_nights_avg_ntm", "has_availability", "availability_30", "availability_60", "availability_90", "availability_365", "calendar_last_scraped", "license"], axis=1)

In [9]:
# Dropping columns for Asheville dataset 
ashe_columns = ashe_unique.drop(["scrape_id", "last_scraped", "host_has_profile_pic", "picture_url", "host_thumbnail_url", "host_picture_url", "host_neighbourhood", "bathrooms",\
     "neighbourhood_group_cleansed", "calendar_updated", "minimum_minimum_nights", "maximum_minimum_nights", "minimum_maximum_nights", "maximum_maximum_nights",\
    "minimum_nights_avg_ntm", "maximum_nights_avg_ntm", "has_availability", "availability_30", "availability_60", "availability_90", "availability_365", "calendar_last_scraped", "license"], axis=1)

In [104]:
# dropping the null rows 
nash_rows = nash_columns.dropna()
nash_rows

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,host_since,host_location,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6422,https://www.airbnb.com/rooms/6422,Nashville Charm,30 day or more rental during COVID. Show COVID...,Historic East Nashville is home to many new an...,12172,https://www.airbnb.com/users/show/12172,Michele,2009-04-03,"Nashville, Tennessee, United States",...,4.97,4.96,4.92,4.98,f,1,0,1,0,4.38
1,39870,https://www.airbnb.com/rooms/39870,Close to Vanderbilt 2,This is a room and private bathroom in my cozy...,"The house is in a safe, quiet, ""college"" neig...",171184,https://www.airbnb.com/users/show/171184,Evelyn,2010-07-18,"San Francisco, California, United States",...,4.99,4.98,4.94,4.94,f,1,0,1,0,4.17
2,72906,https://www.airbnb.com/rooms/72906,Vandy/Belmont/10 mins to Broadway - Sunny 800 ...,Entire top floor. Private. 800 sq ft of bright...,Historic Belmont-Hillsboro neighborhood. Walk-...,176117,https://www.airbnb.com/users/show/176117,Richard Carson,2010-07-21,"Nashville, Tennessee, United States",...,4.98,4.99,4.96,4.88,f,1,1,0,0,4.74
3,258817,https://www.airbnb.com/rooms/258817,ButterflyRoom-private bath- open in oct,Morningstar House! Extended stay - 3+ months- ...,"I'm very near the Percy Priest Lake, natural ...",22296,https://www.airbnb.com/users/show/22296,Diana,2009-06-19,"Nashville, Tennessee, United States",...,4.92,4.90,4.74,4.73,f,7,0,6,1,0.79
4,289242,https://www.airbnb.com/rooms/289242,"MorningstarHouse, monthly room- open sept",Morningstar House! Extended stay - price reduc...,The Morningstar House is in a quiet cul-de-sac...,22296,https://www.airbnb.com/users/show/22296,Diana,2009-06-19,"Nashville, Tennessee, United States",...,4.83,4.78,4.47,4.69,f,7,0,6,1,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6142,53328346,https://www.airbnb.com/rooms/53328346,"Southern Glam, Minutes to Downtown-Sleeps 12","Welcome to “Southern Glam,” a new modern luxur...","Located in East Nashville, literally just over...",319913,https://www.airbnb.com/users/show/319913,Reservations,2010-12-15,"Nashville, Tennessee, United States",...,5.00,5.00,5.00,5.00,f,16,16,0,0,1.00
6146,53357202,https://www.airbnb.com/rooms/53357202,The Forrest Suite - Private Suite in Quiet Area!,This charming one bedroom suite is a perfect h...,This home is located in the cul-de-sac of a ch...,85360355,https://www.airbnb.com/users/show/85360355,StayLocal,2016-07-22,"Nashville, Tennessee, United States",...,5.00,4.75,5.00,5.00,f,81,81,0,0,4.00
6171,53417336,https://www.airbnb.com/rooms/53417336,The Ridley - Cozy Home in Central Location,A spacious yet delightfully cozy feeling 3 bed...,"In the Wedgewood - Houston area, you`ll find y...",85360355,https://www.airbnb.com/users/show/85360355,StayLocal,2016-07-22,"Nashville, Tennessee, United States",...,5.00,5.00,5.00,5.00,f,81,81,0,0,1.00
6173,53419077,https://www.airbnb.com/rooms/53419077,Lux Penthouse Getaway,Lux Gateaway - a modern and luxruious condo. E...,Our place is in a great location downtown! Loc...,85631229,https://www.airbnb.com/users/show/85631229,Alexis,2016-07-24,"Nashville, Tennessee, United States",...,5.00,5.00,5.00,5.00,t,9,9,0,0,1.00
6229,53588853,https://www.airbnb.com/rooms/53588853,Modern Home ★ Super Fun Design ★ Rooftop Terrace,Enjoy our luxury home with 2500 square feet of...,East Nashville has a quirky vibe and a buzzing...,101426897,https://www.airbnb.com/users/show/101426897,Host Extraordinaires,2016-10-26,"Nashville, Tennessee, United States",...,5.00,5.00,5.00,5.00,t,123,123,0,0,1.00

In [105]:
# Asheville columns 
ashe_rows = ashe_columns.dropna()
ashe_rows.shape

(1028, 51)

1. Are there certain zip codes that have noticeably higher ratings than other zip codes?

In [106]:
nash_rows.columns

Index(['id', 'listing_url', 'name', 'description', 'neighborhood_overview',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [71]:
# Renaming the Nashville district code column 

nash_clean = nash_rows.rename(columns={"neighbourhood_cleansed": "district","review_scores_accuracy":"accuracry_review", "review_scores_cleanliness":"cleanliness_review","review_scores_checkin":"checkin_review",\
    "review_scores_communication":"communication_review","review_scores_location":"location_review","review_scores_value":"value_score", "review_scores_rating": "rating_score"})

# reordering the columns 
new_column_order = ["district", "rating_score", "accuracry_review", "cleanliness_review", "checkin_review", "communication_review", "location_review", "value_score"]

nash_clean = nash_clean[new_column_order]

# sorting by the district 
nash_zip_rating_df = nash_clean.sort_values(by=["district"])

len(nash_zip_rating_df) #2692

2692

In [112]:
# findings out how many Nashville districts 
num_nash_districts = nash_zip_rating_df["district"].unique()

num_nash_districts2 = len(num_nash_districts)
# 35

num_nash_districts2

35

In [118]:
# function to find the number of properties per district 
def num_properties_district():
    for i in range(len(num_nash_districts)): 
        print([i])

In [119]:
nash1 = nash_zip_rating_df[nash_zip_rating_df.district == num_properties_district]
nash1

Empty DataFrame
Columns: [district, rating_score, accuracry_review, cleanliness_review, checkin_review, communication_review, location_review, value_score]
Index: []

In [235]:
# Analyzing each individual district 
nash_district_1 = nash_zip_rating_df[nash_zip_rating_df.district == "District 1"]

# mean of all the columns 
nash_district1_avg = nash_district_1.mean()

# creating a dataframe for district 1 
nash_dist_1_df = pd.DataFrame(nash_district1_avg)
nash_dist_1_df

# renaming the column 0 to District 1 
nash1_clean_df = nash_dist_1_df.rename(columns={0:"District 1"})
nash1_updated_df = nash1_clean_df.transpose()

nash1_updated_df["number_properties"]= len(nash_district_1)
nash1_updated_df

flip_nash1 = nash1_updated_df.transpose()

In [234]:
# Nashville District 2 
nash_district_2 = nash_zip_rating_df[nash_zip_rating_df.district == "District 2"]

# Analyzing each individual district 
nash_district_2 = nash_zip_rating_df[nash_zip_rating_df.district == "District 2"]
len(nash_district_2) #22 

# mean of all the columns 
nash_district2_avg = nash_district_2.mean()

# creating a dataframe for district 1 
nash_dist_2_df = pd.DataFrame(nash_district2_avg)
nash_dist_2_df

# renaming the column 0 to District 1 
nash2_clean_df = nash_dist_2_df.rename(columns={0:"District 2"})
nash2_updated_df = nash2_clean_df.transpose()

nash2_updated_df["number_properties"]= len(nash_district_2)
nash2_updated_df

flip_nash2 = nash2_updated_df.transpose()

In [233]:
# Analyzing each individual district 
nash_district_3 = nash_zip_rating_df[nash_zip_rating_df.district == "District 3"]
len(nash_district_3) #22 

# mean of all the columns 
nash_district3_avg = nash_district_3.mean()

# creating a dataframe for district 1 
nash_dist_3_df = pd.DataFrame(nash_district3_avg)
nash_dist_3_df

# renaming the column 0 to District 1 
nash3_clean_df = nash_dist_3_df.rename(columns={0:"District 3"})
nash3_updated_df = nash3_clean_df.transpose()

nash3_updated_df["number_properties"]= len(nash_district_3)
nash3_updated_df

flip_nash3 = nash3_updated_df.transpose()

In [232]:
# Analyzing each individual district 
nash_district_4 = nash_zip_rating_df[nash_zip_rating_df.district == "District 4"]
len(nash_district_4) #22 

# mean of all the columns 
nash_district4_avg = nash_district_4.mean()

# creating a dataframe for district 1 
nash_dist_4_df = pd.DataFrame(nash_district4_avg)
nash_dist_4_df

# renaming the column 0 to District 1 
nash4_clean_df = nash_dist_4_df.rename(columns={0:"District 4"})
nash4_updated_df = nash4_clean_df.transpose()

nash4_updated_df["number_properties"]= len(nash_district_4)
nash4_updated_df

flip_nash4 = nash4_updated_df.transpose()

In [231]:
# Analyzing each individual district 
nash_district_5 = nash_zip_rating_df[nash_zip_rating_df.district == "District 5"]
len(nash_district_5) #22 

# mean of all the columns 
nash_district5_avg = nash_district_5.mean()

# creating a dataframe for district 1 
nash_dist_5_df = pd.DataFrame(nash_district5_avg)
nash_dist_5_df

# renaming the column 0 to District 1 
nash5_clean_df = nash_dist_5_df.rename(columns={0:"District 5"})
nash5_updated_df = nash5_clean_df.transpose()

nash5_updated_df["number_properties"]= len(nash_district_5)
nash5_updated_df

flip_nash5 = nash5_updated_df.transpose()

In [230]:
# Analyzing each individual district 
nash_district_6 = nash_zip_rating_df[nash_zip_rating_df.district == "District 6"]
len(nash_district_6) #22 

# mean of all the columns 
nash_district6_avg = nash_district_6.mean()

# creating a dataframe for district 1 
nash_dist_6_df = pd.DataFrame(nash_district6_avg)
nash_dist_6_df

# renaming the column 0 to District 1 
nash6_clean_df = nash_dist_6_df.rename(columns={0:"District 6"})
nash6_updated_df = nash6_clean_df.transpose()

nash6_updated_df["number_properties"]= len(nash_district_6)
nash6_updated_df

flip_nash6 = nash6_updated_df.transpose()

In [229]:
# Analyzing each individual district 
nash_district_7 = nash_zip_rating_df[nash_zip_rating_df.district == "District 7"]

# mean of all the columns 
nash_district7_avg = nash_district_7.mean()

# creating a dataframe for district 1 
nash_dist_7_df = pd.DataFrame(nash_district7_avg)
nash_dist_7_df

# renaming the column 0 to District 1 
nash7_clean_df = nash_dist_7_df.rename(columns={0:"District 7"})
nash7_updated_df = nash7_clean_df.transpose()

nash7_updated_df["number_properties"]= len(nash_district_7)
nash7_updated_df

flip_nash7 = nash7_updated_df.transpose()

In [228]:
# Analyzing each individual district 
nash_district_8 = nash_zip_rating_df[nash_zip_rating_df.district == "District 8"]
len(nash_district_8)  

# mean of all the columns 
nash_district8_avg = nash_district_8.mean()

# creating a dataframe for district 1 
nash_dist_8_df = pd.DataFrame(nash_district8_avg)
nash_dist_8_df

# renaming the column 0 to District 1 
nash8_clean_df = nash_dist_8_df.rename(columns={0:"District 8"})
nash8_updated_df = nash8_clean_df.transpose()

nash8_updated_df["number_properties"]= len(nash_district_8)
nash8_updated_df

flip_nash8 = nash8_updated_df.transpose()

In [227]:
# Analyzing each individual district 
nash_district_9 = nash_zip_rating_df[nash_zip_rating_df.district == "District 9"]
len(nash_district_9) 

# mean of all the columns 
nash_district9_avg = nash_district_9.mean()

# creating a dataframe for district 1 
nash_dist_9_df = pd.DataFrame(nash_district9_avg)
nash_dist_9_df

# renaming the column 0 to District 1 
nash9_clean_df = nash_dist_9_df.rename(columns={0:"District 9"})
nash9_updated_df = nash9_clean_df.transpose()

nash9_updated_df["number_properties"]= len(nash_district_9)
nash9_updated_df

flip_nash9 = nash9_updated_df.transpose()

In [226]:
# Analyzing each individual district 
nash_district_10 = nash_zip_rating_df[nash_zip_rating_df.district == "District 10"]
len(nash_district_10) 

# mean of all the columns 
nash_district10_avg = nash_district_10.mean()

# creating a dataframe for district 1 
nash_dist_10_df = pd.DataFrame(nash_district10_avg)
nash_dist_10_df

# renaming the column 0 to District 1 
nash10_clean_df = nash_dist_10_df.rename(columns={0:"District 10"})
nash10_updated_df = nash10_clean_df.transpose()

nash10_updated_df["number_properties"]= len(nash_district_10)
nash10_updated_df

flip_nash10 = nash10_updated_df.transpose()

In [225]:
# Analyzing each individual district 
nash_district_11 = nash_zip_rating_df[nash_zip_rating_df.district == "District 11"]
len(nash_district_11) 

# mean of all the columns 
nash_district11_avg = nash_district_11.mean()

# creating a dataframe for district 1 
nash_dist_11_df = pd.DataFrame(nash_district11_avg)
nash_dist_11_df

# renaming the column 0 to District 1 
nash11_clean_df = nash_dist_11_df.rename(columns={0:"District 11"})
nash11_updated_df = nash11_clean_df.transpose()

nash11_updated_df["number_properties"]= len(nash_district_11)
nash11_updated_df

flip_nash11 = nash11_updated_df.transpose()

In [224]:
# Analyzing each individual district 
nash_district_12 = nash_zip_rating_df[nash_zip_rating_df.district == "District 12"]
len(nash_district_12) 

# mean of all the columns 
nash_district12_avg = nash_district_12.mean()

# creating a dataframe for district 1 
nash_dist_12_df = pd.DataFrame(nash_district12_avg)
nash_dist_12_df

# renaming the column 0 to District 1 
nash12_clean_df = nash_dist_12_df.rename(columns={0:"District 12"})
nash12_updated_df = nash12_clean_df.transpose()

nash12_updated_df["number_properties"]= len(nash_district_12)
nash12_updated_df

flip_nash12 = nash12_updated_df.transpose()

In [223]:
# Analyzing each individual district 
nash_district_13 = nash_zip_rating_df[nash_zip_rating_df.district == "District 13"]
len(nash_district_13) 

# mean of all the columns 
nash_district13_avg = nash_district_13.mean()

# creating a dataframe for district 1 
nash_dist_13_df = pd.DataFrame(nash_district13_avg)
nash_dist_13_df

# renaming the column 0 to District 1 
nash13_clean_df = nash_dist_13_df.rename(columns={0:"District 13"})
nash13_updated_df = nash13_clean_df.transpose()

nash13_updated_df["number_properties"]= len(nash_district_13)
nash13_updated_df

flip_nash13 = nash13_updated_df.transpose()

In [222]:
# Analyzing each individual district 
nash_district_14 = nash_zip_rating_df[nash_zip_rating_df.district == "District 14"]
len(nash_district_14) 

# mean of all the columns 
nash_district14_avg = nash_district_14.mean()

# creating a dataframe for district 1 
nash_dist_14_df = pd.DataFrame(nash_district14_avg)
nash_dist_14_df

# renaming the column 0 to District 1 
nash14_clean_df = nash_dist_14_df.rename(columns={0:"District 14"})
nash14_updated_df = nash14_clean_df.transpose()

nash14_updated_df["number_properties"]= len(nash_district_14)
nash14_updated_df

flip_nash14 = nash14_updated_df.transpose()

In [221]:
# Analyzing each individual district 
nash_district_15 = nash_zip_rating_df[nash_zip_rating_df.district == "District 15"]
len(nash_district_15) 

# mean of all the columns 
nash_district15_avg = nash_district_15.mean()

# creating a dataframe for district 1 
nash_dist_15_df = pd.DataFrame(nash_district15_avg)
nash_dist_15_df

# renaming the column 0 to District 1 
nash15_clean_df = nash_dist_15_df.rename(columns={0:"District 15"})
nash15_updated_df = nash15_clean_df.transpose()

nash15_updated_df["number_properties"]= len(nash_district_15)
nash15_updated_df

flip_nash15 = nash15_updated_df.transpose()

In [220]:
# Analyzing each individual district 
nash_district_16 = nash_zip_rating_df[nash_zip_rating_df.district == "District 16"]
len(nash_district_16) 

# mean of all the columns 
nash_district16_avg = nash_district_16.mean()

# creating a dataframe for district 1 
nash_dist_16_df = pd.DataFrame(nash_district16_avg)
nash_dist_16_df

# renaming the column 0 to District 1 
nash16_clean_df = nash_dist_16_df.rename(columns={0:"District 16"})
nash16_updated_df = nash16_clean_df.transpose()

nash16_updated_df["number_properties"]= len(nash_district_16)
nash16_updated_df

flip_nash16 = nash16_updated_df.transpose()

In [217]:
# Analyzing each individual district 
nash_district_17 = nash_zip_rating_df[nash_zip_rating_df.district == "District 17"]
len(nash_district_17) 

# mean of all the columns 
nash_district17_avg = nash_district_17.mean()

# creating a dataframe for district 1 
nash_dist_17_df = pd.DataFrame(nash_district17_avg)
nash_dist_17_df

# renaming the column 0 to District 1 
nash17_clean_df = nash_dist_17_df.rename(columns={0:"District 17"})
nash17_updated_df = nash17_clean_df.transpose()

nash17_updated_df["number_properties"]= len(nash_district_17)
nash17_updated_df

flip_nash17 = nash17_updated_df.transpose()

In [216]:
# Analyzing each individual district 
nash_district_18 = nash_zip_rating_df[nash_zip_rating_df.district == "District 18"]
len(nash_district_18) 

# mean of all the columns 
nash_district18_avg = nash_district_18.mean()

# creating a dataframe for district 1 
nash_dist_18_df = pd.DataFrame(nash_district18_avg)
nash_dist_18_df

# renaming the column 0 to District 1 
nash18_clean_df = nash_dist_18_df.rename(columns={0:"District 18"})
nash18_updated_df = nash18_clean_df.transpose()

nash18_updated_df["number_properties"]= len(nash_district_18)
nash18_updated_df

flip_nash18 = nash18_updated_df.transpose()

In [215]:
# Analyzing each individual district 
nash_district_19 = nash_zip_rating_df[nash_zip_rating_df.district == "District 19"]
len(nash_district_19) 

# mean of all the columns 
nash_district19_avg = nash_district_19.mean()

# creating a dataframe for district 1 
nash_dist_19_df = pd.DataFrame(nash_district19_avg)
nash_dist_19_df

# renaming the column 0 to District 1 
nash19_clean_df = nash_dist_19_df.rename(columns={0:"District 19"})
nash19_updated_df = nash19_clean_df.transpose()

nash19_updated_df["number_properties"]= len(nash_district_19)
nash19_updated_df

flip_nash19 = nash19_updated_df.transpose()

In [214]:
# Analyzing each individual district 
nash_district_20 = nash_zip_rating_df[nash_zip_rating_df.district == "District 20"]
len(nash_district_20) 

# mean of all the columns 
nash_district20_avg = nash_district_20.mean()

# creating a dataframe for district 1 
nash_dist_20_df = pd.DataFrame(nash_district20_avg)
nash_dist_20_df

# renaming the column 0 to District 1 
nash20_clean_df = nash_dist_20_df.rename(columns={0:"District 20"})
nash20_updated_df = nash20_clean_df.transpose()

nash20_updated_df["number_properties"]= len(nash_district_20)
nash20_updated_df

flip_nash20 = nash20_updated_df.transpose()

In [213]:
# Analyzing each individual district 
nash_district_21 = nash_zip_rating_df[nash_zip_rating_df.district == "District 21"]
len(nash_district_21) 

# mean of all the columns 
nash_district21_avg = nash_district_21.mean()

# creating a dataframe for district 1 
nash_dist_21_df = pd.DataFrame(nash_district21_avg)
nash_dist_21_df

# renaming the column 0 to District 1 
nash21_clean_df = nash_dist_21_df.rename(columns={0:"District 21"})
nash21_updated_df = nash21_clean_df.transpose()

nash21_updated_df["number_properties"]= len(nash_district_21)
nash21_updated_df

flip_nash21 = nash21_updated_df.transpose()

In [212]:
# Analyzing each individual district 
nash_district_22 = nash_zip_rating_df[nash_zip_rating_df.district == "District 22"]
len(nash_district_22) 

# mean of all the columns 
nash_district22_avg = nash_district_22.mean()

# creating a dataframe for district 1 
nash_dist_22_df = pd.DataFrame(nash_district22_avg)
nash_dist_22_df

# renaming the column 0 to District 1 
nash22_clean_df = nash_dist_22_df.rename(columns={0:"District 22"})
nash22_updated_df = nash22_clean_df.transpose()

nash22_updated_df["number_properties"]= len(nash_district_22)
nash22_updated_df

flip_nash22 = nash22_updated_df.transpose()

In [210]:
# Analyzing each individual district 
nash_district_23 = nash_zip_rating_df[nash_zip_rating_df.district == "District 23"]
len(nash_district_23) 

# mean of all the columns 
nash_district23_avg = nash_district_23.mean()

# creating a dataframe for district 1 
nash_dist_23_df = pd.DataFrame(nash_district23_avg)
nash_dist_23_df

# renaming the column 0 to District 1 
nash23_clean_df = nash_dist_23_df.rename(columns={0:"District 23"})
nash23_updated_df = nash23_clean_df.transpose()

nash23_updated_df["number_properties"]= len(nash_district_23)
nash23_updated_df

flip_nash23 = nash23_updated_df.transpose()

In [209]:
# Analyzing each individual district 
nash_district_24 = nash_zip_rating_df[nash_zip_rating_df.district == "District 24"]
len(nash_district_24) 

# mean of all the columns 
nash_district24_avg = nash_district_24.mean()

# creating a dataframe for district 1 
nash_dist_24_df = pd.DataFrame(nash_district24_avg)
nash_dist_24_df

# renaming the column 0 to District 1 
nash24_clean_df = nash_dist_24_df.rename(columns={0:"District 24"})
nash24_updated_df = nash24_clean_df.transpose()

nash24_updated_df["number_properties"]= len(nash_district_24)
nash24_updated_df

flip_nash24 = nash24_updated_df.transpose()

In [208]:
# Analyzing each individual district 
nash_district_25 = nash_zip_rating_df[nash_zip_rating_df.district == "District 25"]
len(nash_district_25) 

# mean of all the columns 
nash_district25_avg = nash_district_25.mean()

# creating a dataframe for district 1 
nash_dist_25_df = pd.DataFrame(nash_district25_avg)
nash_dist_25_df

# renaming the column 0 to District 1 
nash25_clean_df = nash_dist_25_df.rename(columns={0:"District 25"})
nash25_updated_df = nash25_clean_df.transpose()

nash25_updated_df["number_properties"]= len(nash_district_25)
nash25_updated_df

flip_nash25 = nash25_updated_df.transpose()

In [207]:
# Analyzing each individual district 
nash_district_26 = nash_zip_rating_df[nash_zip_rating_df.district == "District 26"]
len(nash_district_26) 

# mean of all the columns 
nash_district26_avg = nash_district_26.mean()

# creating a dataframe for district 1 
nash_dist_26_df = pd.DataFrame(nash_district26_avg)
nash_dist_26_df

# renaming the column 0 to District 1 
nash26_clean_df = nash_dist_26_df.rename(columns={0:"District 26"})
nash26_updated_df = nash26_clean_df.transpose()

nash26_updated_df["number_properties"]= len(nash_district_26)
nash26_updated_df

flip_nash26 = nash26_updated_df.transpose()

In [206]:
# Analyzing each individual district 
nash_district_27 = nash_zip_rating_df[nash_zip_rating_df.district == "District 27"]
len(nash_district_27) 

# mean of all the columns 
nash_district27_avg = nash_district_27.mean()

# creating a dataframe for district 1 
nash_dist_27_df = pd.DataFrame(nash_district27_avg)
nash_dist_27_df

# renaming the column 0 to District 1 
nash27_clean_df = nash_dist_27_df.rename(columns={0:"District 27"})
nash27_updated_df = nash27_clean_df.transpose()

nash27_updated_df["number_properties"]= len(nash_district_27)
nash27_updated_df

flip_nash27 = nash27_updated_df.transpose()

In [205]:
# Analyzing each individual district 
nash_district_28 = nash_zip_rating_df[nash_zip_rating_df.district == "District 28"]
len(nash_district_28) 

# mean of all the columns 
nash_district28_avg = nash_district_28.mean()

# creating a dataframe for district 1 
nash_dist_28_df = pd.DataFrame(nash_district28_avg)
nash_dist_28_df

# renaming the column 0 to District 1 
nash28_clean_df = nash_dist_28_df.rename(columns={0:"District 28"})
nash28_updated_df = nash28_clean_df.transpose()

nash28_updated_df["number_properties"]= len(nash_district_28)
nash28_updated_df

flip_nash28 = nash28_updated_df.transpose()

In [204]:
# Analyzing each individual district 
nash_district_29 = nash_zip_rating_df[nash_zip_rating_df.district == "District 29"]
len(nash_district_29) 

# mean of all the columns 
nash_district29_avg = nash_district_29.mean()

# creating a dataframe for district 1 
nash_dist_29_df = pd.DataFrame(nash_district29_avg)
nash_dist_29_df

# renaming the column 0 to District 1 
nash29_clean_df = nash_dist_29_df.rename(columns={0:"District 29"})
nash29_updated_df = nash29_clean_df.transpose()

nash29_updated_df["number_properties"]= len(nash_district_29)
nash29_updated_df

flip_nash29 = nash29_updated_df.transpose()

In [203]:
# Analyzing each individual district 
nash_district_30 = nash_zip_rating_df[nash_zip_rating_df.district == "District 30"]
len(nash_district_30) 

# mean of all the columns 
nash_district30_avg = nash_district_30.mean()

# creating a dataframe for district 1 
nash_dist_30_df = pd.DataFrame(nash_district30_avg)
nash_dist_30_df

# renaming the column 0 to District 1 
nash30_clean_df = nash_dist_30_df.rename(columns={0:"District 30"})
nash30_updated_df = nash30_clean_df.transpose()

nash30_updated_df["number_properties"]= len(nash_district_30)
nash30_updated_df

flip_nash30 = nash30_updated_df.transpose()

In [202]:
# Analyzing each individual district 
nash_district_31 = nash_zip_rating_df[nash_zip_rating_df.district == "District 31"]
len(nash_district_31) 

# mean of all the columns 
nash_district31_avg = nash_district_31.mean()

# creating a dataframe for district 
nash_dist_31_df = pd.DataFrame(nash_district31_avg)
nash_dist_31_df

# renaming the column 0 to District  
nash31_clean_df = nash_dist_31_df.rename(columns={0:"District 31"})
nash31_updated_df = nash31_clean_df.transpose()

nash31_updated_df["number_properties"]= len(nash_district_31)
nash31_updated_df

flip_nash31 = nash31_updated_df.transpose()

In [201]:
# Analyzing each individual district 
nash_district_32 = nash_zip_rating_df[nash_zip_rating_df.district == "District 32"]
len(nash_district_32) 

# mean of all the columns 
nash_district32_avg = nash_district_32.mean()

# creating a dataframe for district 1 
nash_dist_32_df = pd.DataFrame(nash_district32_avg)
nash_dist_32_df

# renaming the column 0 to District 1 
nash32_clean_df = nash_dist_32_df.rename(columns={0:"District 32"})
nash32_updated_df = nash32_clean_df.transpose()

nash32_updated_df["number_properties"]= len(nash_district_32)
nash32_updated_df

flip_nash32 = nash32_updated_df.transpose()

In [200]:
# Analyzing each individual district 
nash_district_33 = nash_zip_rating_df[nash_zip_rating_df.district == "District 33"]
len(nash_district_33) 

# mean of all the columns 
nash_district33_avg = nash_district_33.mean()

# creating a dataframe for district 1 
nash_dist_33_df = pd.DataFrame(nash_district33_avg)
nash_dist_33_df

# renaming the column 0 to District 1 
nash33_clean_df = nash_dist_33_df.rename(columns={0:"District 33"})
nash33_updated_df = nash33_clean_df.transpose()

nash33_updated_df["number_properties"]= len(nash_district_33)
nash33_updated_df

flip_nash33 = nash33_updated_df.transpose()

In [194]:
# Analyzing each individual district 
nash_district_34 = nash_zip_rating_df[nash_zip_rating_df.district == "District 34"]
len(nash_district_34) 

# mean of all the columns 
nash_district34_avg = nash_district_34.mean()

# creating a dataframe for district 1 
nash_dist_34_df = pd.DataFrame(nash_district34_avg)
nash_dist_34_df

# renaming the column 0 to District 1 
nash34_clean_df = nash_dist_34_df.rename(columns={0:"District 34"})
nash34_updated_df = nash34_clean_df.transpose()

nash34_updated_df["number_properties"]= len(nash_district_34)
nash34_updated_df

flip_nash34 = nash34_updated_df.transpose()

In [193]:
# Analyzing each individual district 
nash_district_35 = nash_zip_rating_df[nash_zip_rating_df.district == "District 35"]
len(nash_district_35) 

# mean of all the columns 
nash_district35_avg = nash_district_35.mean()

# creating a dataframe for district 1 
nash_dist_35_df = pd.DataFrame(nash_district35_avg)
nash_dist_35_df

# renaming the column 0 to District 1 
nash35_clean_df = nash_dist_35_df.rename(columns={0:"District 35"})
nash35_updated_df = nash35_clean_df.transpose()

nash35_updated_df["number_properties"]= len(nash_district_35)
nash35_updated_df
flip_nash35 = nash35_updated_df.transpose()
flip_nash35

                      District 35
rating_score             4.843846
accuracry_review         4.881538
cleanliness_review       4.790000
checkin_review           4.959231
communication_review     4.890769
location_review          4.876923
value_score              4.854615
number_properties       13.000000

In [307]:
# Joining all the district dataframes 
frames = [flip_nash35, flip_nash34, flip_nash33, flip_nash32, flip_nash31, flip_nash30, flip_nash29, flip_nash28, flip_nash27, flip_nash26, flip_nash25, flip_nash24, flip_nash23,\
            flip_nash22, flip_nash21, flip_nash20, flip_nash19, flip_nash18, flip_nash17, flip_nash16, flip_nash15, flip_nash14, flip_nash13, flip_nash12, flip_nash11, flip_nash10,\
                flip_nash9,flip_nash8, flip_nash7, flip_nash6, flip_nash5, flip_nash4, flip_nash3, flip_nash2, flip_nash1]
complete_nashville_df = pd.concat(frames, axis=1)

nashville_df = complete_nashville_df.transpose()
nashville_df.sort_values(by=['rating_score'])

,rating_score,accuracry_review,cleanliness_review,checkin_review,communication_review,location_review,value_score,number_properties
District 14,4.762273,4.838182,4.798182,4.913636,4.802273,4.673636,4.752727,22.0
District 30,4.763846,4.835385,4.676154,4.938462,4.917692,4.710000,4.763846,13.0
District 32,4.775000,4.810000,4.841667,4.908333,4.885000,4.843333,4.838333,6.0
District 34,4.777500,4.932500,4.817500,4.967500,4.972500,4.945000,4.785000,4.0
District 22,4.783750,4.907500,4.806250,4.933750,4.953750,4.835000,4.827500,8.0
District 2,4.786757,4.833514,4.737703,4.861622,4.875946,4.632297,4.769054,74.0
District 28,4.794286,4.837143,4.798571,4.947143,4.927143,4.754286,4.822857,7.0
District 15,4.795732,4.839024,4.824024,4.886098,4.859146,4.829878,4.744390,82.0
District 11,4.797500,4.807500,4.660000,4.973750,4.971250,4.643750,4.920000,8.0
District 21,4.797569,4.837294,4.772078,4.898431,4.893255,4.670863,4.758588,255.0
District 19,4.808919,4.858156,4.818029,4.856693,4.889650,4.799269,4.738045,629.0
District 12,4.821818,4.836364,4.641818,4.932273,4.917727,4.798182,4.769091,22.0
District 18,4.828426,4.870833,4.837315,4.889537,4.888148,4.899352,4.779074,108.0
District 35,4.843846,4.881538,4.790000,4.959231,4.890769,4.876923,4.854615,13.0
District 16,4.845574,4.901475,4.807541,4.960000,4.951475,4.763770,4.810328,61.0
District 13,4.865357,4.907143,4.806786,4.941071,4.945357,4.850714,4.847500,28.0
District 24,4.870000,4.895357,4.853036,4.954464,4.941071,4.883571,4.836071,56.0
District 20,4.876579,4.904342,4.833421,4.930000,4.931053,4.807237,4.858026,76.0
District 9,4.878333,4.863333,4.895000,4.935000,4.940000,4.691667,4.846667,6.0
District 5,4.881800,4.902933,4.851267,4.951967,4.939300,4.764833,4.823400,300.0
District 31,4.882500,4.942500,4.950000,4.945000,4.907500,4.850000,4.925000,4.0
District 27,4.883750,4.906250,4.877500,4.971250,4.903750,4.821250,4.853750,8.0
District 26,4.883889,4.918333,4.878889,4.954444,4.943889,4.839444,4.866667,18.0
District 17,4.887112,4.909544,4.848602,4.936261,4.936201,4.850456,4.825015,329.0
District 23,4.888571,4.875714,4.872857,4.947143,4.930000,4.884286,4.825714,7.0
District 4,4.891111,4.945556,4.922222,4.961111,4.955556,4.845556,4.885556,9.0
District 8,4.898966,4.948621,4.840517,4.972759,4.962586,4.875000,4.902759,58.0
District 7,4.904074,4.922000,4.890074,4.958667,4.951111,4.823333,4.865407,135.0
District 6,4.905984,4.920643,4.889719,4.948394,4.944458,4.908233,4.844618,249.0
District 29,4.908333,4.932778,4.903889,4.966111,4.935000,4.826111,4.873889,18.0
District 3,4.918333,4.965833,4.875000,4.963333,4.954167,4.849167,4.790000,12.0
District 25,4.918966,4.942414,4.921724,4.959310,4.949310,4.950345,4.862414,29.0
District 1,4.919091,4.933636,4.867727,4.970455,4.963636,4.855000,4.911818,22.0
District 10,4.944615,4.892308,4.945385,4.994615,4.929231,4.913846,4.852308,13.0
District 33,4.986667,4.986667,4.650000,4.990000,4.996667,4.960000,4.973333,3.0

In [310]:
nashville_df.describe()

,rating_score,accuracry_review,cleanliness_review,checkin_review,communication_review,location_review,value_score,number_properties
count,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000
mean,4.856481,4.892638,4.828584,4.942223,4.927302,4.820731,4.834382,76.914286
std,0.057451,0.046161,0.078738,0.032678,0.037589,0.085137,0.055944,130.248715
min,4.762273,4.807500,4.641818,4.856693,4.802273,4.632297,4.738045,3.000000
25%,4.797534,4.848590,4.802411,4.933011,4.905625,4.781508,4.787500,8.000000
50%,4.876579,4.902933,4.840517,4.948394,4.936201,4.839444,4.838333,22.000000
75%,4.895038,4.927250,4.878194,4.962222,4.951293,4.875962,4.863911,75.000000
max,4.986667,4.986667,4.950000,4.994615,4.996667,4.960000,4.973333,629.000000

In [301]:
# Start to explore correlations within the data for Nashville "reviews_scores_rating" for total rating - correlation
correlations_nash=nash_rows.corr()
correlations_nash=correlations_nash["review_scores_rating"].sort_values(ascending=False)
features=correlations_nash.index[1:6]
correlations_nash

review_scores_rating                            1.000000
review_scores_accuracy                          0.868489
review_scores_value                             0.863821
review_scores_communication                     0.823744
review_scores_cleanliness                       0.809785
review_scores_checkin                           0.748340
review_scores_location                          0.632192
number_of_reviews                               0.090247
reviews_per_month                               0.075220
number_of_reviews_l30d                          0.068485
number_of_reviews_ltm                           0.063343
bedrooms                                        0.042809
latitude                                        0.034839
longitude                                       0.032403
accommodates                                    0.025618
beds                                            0.024949
host_id                                         0.020105
calculated_host_listings_count_shared_rooms    -0.025216
maximum_nights                                 -0.032297
calculated_host_listings_count_private_rooms   -0.046884
minimum_nights                                 -0.061422
id                                             -0.095797
calculated_host_listings_count_entire_homes    -0.140939
calculated_host_listings_count                 -0.142271
host_total_listings_count                      -0.404534
host_listings_count                            -0.404534
Name: review_scores_rating, dtype: float64

In [303]:
# Explore correlation in host listing count versus other characteristics in the Nashville data
correlations_nash_host=nash_rows.corr()
correlations_nash_host=correlations_nash_host["host_listings_count"].sort_values(ascending=False)
features=correlations_nash_host.index[1:6]
correlations_nash_host

host_listings_count                             1.000000
host_total_listings_count                       1.000000
calculated_host_listings_count                  0.213100
calculated_host_listings_count_entire_homes     0.188642
calculated_host_listings_count_private_rooms    0.185047
id                                              0.132245
beds                                            0.066005
accommodates                                    0.065796
bedrooms                                        0.048703
longitude                                       0.035944
maximum_nights                                  0.031888
calculated_host_listings_count_shared_rooms    -0.008167
latitude                                       -0.018608
minimum_nights                                 -0.029365
host_id                                        -0.047489
number_of_reviews_l30d                         -0.062335
number_of_reviews_ltm                          -0.091123
reviews_per_month                              -0.092437
number_of_reviews                              -0.100169
review_scores_location                         -0.274270
review_scores_cleanliness                      -0.301272
review_scores_accuracy                         -0.336433
review_scores_checkin                          -0.375336
review_scores_rating                           -0.404534
review_scores_value                            -0.416634
review_scores_communication                    -0.427238
Name: host_listings_count, dtype: float64

In [306]:
# Does the description accuracy of the listing correlate with a higher rating in any category for the Nashville data?
correlations_nash_accuracy=nash_rows.corr()
correlations_nash_accuracy=correlations_nash_accuracy["review_scores_accuracy"].sort_values(ascending=False)
features=correlations_nash_accuracy.index[1:6]
correlations_nash_accuracy

review_scores_accuracy                          1.000000
review_scores_rating                            0.868489
review_scores_value                             0.784694
review_scores_communication                     0.755550
review_scores_cleanliness                       0.745546
review_scores_checkin                           0.715890
review_scores_location                          0.584320
reviews_per_month                               0.117896
number_of_reviews                               0.116380
number_of_reviews_l30d                          0.098785
number_of_reviews_ltm                           0.098375
host_id                                         0.033810
longitude                                       0.029334
latitude                                        0.013276
bedrooms                                        0.003248
accommodates                                   -0.009342
beds                                           -0.011526
calculated_host_listings_count_shared_rooms    -0.022082
calculated_host_listings_count_private_rooms   -0.023424
maximum_nights                                 -0.040772
id                                             -0.085053
minimum_nights                                 -0.090512
calculated_host_listings_count                 -0.129155
calculated_host_listings_count_entire_homes    -0.129981
host_total_listings_count                      -0.336433
host_listings_count                            -0.336433
Name: review_scores_accuracy, dtype: float64

Asheville Data

In [261]:
# Renaming the Nashville district code column 

ashe_clean = ashe_rows.rename(columns={"neighbourhood_cleansed": "district","review_scores_accuracy":"accuracry_review", "review_scores_cleanliness":"cleanliness_review","review_scores_checkin":"checkin_review",\
    "review_scores_communication":"communication_review","review_scores_location":"location_review","review_scores_value":"value_score", "review_scores_rating": "rating_score"})

# reordering the columns 
new_column_order1 = ["district", "rating_score", "accuracry_review", "cleanliness_review", "checkin_review", "communication_review", "location_review", "value_score"]

ashe_clean = ashe_clean[new_column_order1]

# sorting by the district 
ashe_zip_rating_df = ashe_clean.sort_values(by=["district"])

len(ashe_zip_rating_df) #1028

ashe_zip_rating_df

,district,rating_score,accuracry_review,cleanliness_review,checkin_review,communication_review,location_review,value_score
180,28704,4.80,4.88,4.70,4.96,4.96,4.85,4.91
1781,28704,4.44,4.61,4.94,4.89,4.67,4.83,4.44
167,28704,4.97,4.96,4.97,4.99,4.97,4.88,4.91
2001,28704,5.00,4.95,4.95,5.00,5.00,4.91,4.82
1746,28704,4.95,4.93,4.91,4.98,5.00,4.91,4.91
...,...,...,...,...,...,...,...,...
1437,28806,4.88,4.91,4.97,4.99,4.99,4.96,4.89
441,28806,4.86,4.96,4.80,4.95,4.97,4.89,4.90
1414,28806,4.72,4.80,4.77,4.93,4.90,4.64,4.69
1404,28806,4.89,4.94,4.97,4.99,4.99,4.97,4.85
2597,28806,5.00,5.00,5.00,5.00,5.00,5.00,5.00

In [263]:
# findings out how many Asheville districts 
num_ashe_districts = ashe_zip_rating_df["district"].unique()
num_ashe_districts

# num_ashe_districts2 = len(num_ashe_districts)

# num_ashe_districts2 # 8

array([28704, 28715, 28732, 28801, 28803, 28804, 28805, 28806])

In [289]:
# Analyzing each individual district 
ashe_district_28704 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28704]

# mean of all the columns 
ashe_district28704_avg = ashe_district_28704.mean()

# creating a dataframe for district 1 
ashe_dist_28704_df = pd.DataFrame(ashe_district28704_avg)
ashe_dist_28704_df

# renaming the column 0 to District 1 
ashe28704_clean_df = ashe_dist_28704_df.rename(columns={0:"District 28704"})
ashe28704_updated_df = ashe28704_clean_df.transpose()

ashe28704_updated_df["number_properties"]= len(ashe_district_28704)
ashe28704_updated_df

flip_ashe28704 = ashe28704_updated_df.transpose()

flip_ashe28704

                      District 28704
district                28704.000000
rating_score                4.875455
accuracry_review            4.896182
cleanliness_review          4.876909
checkin_review              4.971091
communication_review        4.951273
location_review             4.869091
value_score                 4.806727
number_properties          55.000000

In [290]:
# Analyzing each individual district 
ashe_district_28715 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28715]

# mean of all the columns 
ashe_district28715_avg = ashe_district_28715.mean()

# creating a dataframe for district 1 
ashe_dist_28715_df = pd.DataFrame(ashe_district28715_avg)
ashe_dist_28715_df

# renaming the column 0 to District 1 
ashe28715_clean_df = ashe_dist_28715_df.rename(columns={0:"District 28715"})
ashe28715_updated_df = ashe28715_clean_df.transpose()

ashe28715_updated_df["number_properties"]= len(ashe_district_28715)
ashe28715_updated_df

flip_ashe28715 = ashe28715_updated_df.transpose()

In [291]:
# Analyzing each individual district 
ashe_district_28732 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28732]

# mean of all the columns 
ashe_district28732_avg = ashe_district_28732.mean()

# creating a dataframe for district 1 
ashe_dist_28732_df = pd.DataFrame(ashe_district28732_avg)
ashe_dist_28732_df

# renaming the column 0 to District 1 
ashe28732_clean_df = ashe_dist_28732_df.rename(columns={0:"District 28732"})
ashe28732_updated_df = ashe28732_clean_df.transpose()

ashe28732_updated_df["number_properties"]= len(ashe_district_28732)
ashe28732_updated_df

flip_ashe28732 = ashe28732_updated_df.transpose()

In [298]:
# Analyzing each individual district 
ashe_district_28801 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28801]

# mean of all the columns 
ashe_district28801_avg = ashe_district_28801.mean()

# creating a dataframe for district 1 
ashe_dist_28801_df = pd.DataFrame(ashe_district28801_avg)
ashe_dist_28801_df

# renaming the column 0 to District 1 
ashe28801_clean_df = ashe_dist_28801_df.rename(columns={0:"District 28801"})
ashe28801_updated_df = ashe28801_clean_df.transpose()

ashe28801_updated_df["number_properties"]= len(ashe_district_28801)
ashe28801_updated_df

flip_ashe28801 = ashe28801_updated_df.transpose()

In [293]:
# Analyzing each individual district 
ashe_district_28803 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28803]

# mean of all the columns 
ashe_district28803_avg = ashe_district_28803.mean()

# creating a dataframe for district 1 
ashe_dist_28803_df = pd.DataFrame(ashe_district28803_avg)
ashe_dist_28803_df

# renaming the column 0 to District 1 
ashe28803_clean_df = ashe_dist_28803_df.rename(columns={0:"District 28803"})
ashe28803_updated_df = ashe28803_clean_df.transpose()

ashe28803_updated_df["number_properties"]= len(ashe_district_28803)
ashe28803_updated_df

flip_ashe28803 = ashe28803_updated_df.transpose()

In [294]:
# Analyzing each individual district 
ashe_district_28804 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28804]

# mean of all the columns 
ashe_district28804_avg = ashe_district_28804.mean()

# creating a dataframe for district  
ashe_dist_28804_df = pd.DataFrame(ashe_district28804_avg)
ashe_dist_28804_df

# renaming the column 0 to District 1 
ashe28804_clean_df = ashe_dist_28804_df.rename(columns={0:"District 28804"})
ashe28804_updated_df = ashe28804_clean_df.transpose()

ashe28804_updated_df["number_properties"]= len(ashe_district_28804)
ashe28804_updated_df

flip_ashe28804 = ashe28804_updated_df.transpose()

In [295]:
# Analyzing each individual district 
ashe_district_28805 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28805]

# mean of all the columns 
ashe_district28805_avg = ashe_district_28805.mean()

# creating a dataframe for district 1 
ashe_dist_28805_df = pd.DataFrame(ashe_district28805_avg)
ashe_dist_28805_df

# renaming the column 0 to District 1 
ashe28805_clean_df = ashe_dist_28805_df.rename(columns={0:"District 28805"})
ashe28805_updated_df = ashe28805_clean_df.transpose()

ashe28805_updated_df["number_properties"]= len(ashe_district_28805)
ashe28805_updated_df

flip_ashe28805 = ashe28805_updated_df.transpose()

In [296]:
# Analyzing each individual district 
ashe_district_28806 = ashe_zip_rating_df[ashe_zip_rating_df.district == 28806]

# mean of all the columns 
ashe_district28806_avg = ashe_district_28806.mean()

# creating a dataframe for district 1 
ashe_dist_28806_df = pd.DataFrame(ashe_district28806_avg)
ashe_dist_28806_df

# renaming the column 0 to District 1 
ashe28806_clean_df = ashe_dist_28806_df.rename(columns={0:"District 28806"})
ashe28806_updated_df = ashe28806_clean_df.transpose()

ashe28806_updated_df["number_properties"]= len(ashe_district_28806)
ashe28806_updated_df

flip_ashe28806 = ashe28806_updated_df.transpose()
flip_ashe28806

                      District 28806
district                28806.000000
rating_score                4.896623
accuracry_review            4.924735
cleanliness_review          4.914437
checkin_review              4.966821
communication_review        4.955662
location_review             4.877517
value_score                 4.844503
number_properties         302.000000

In [309]:
# Joining all the district dataframes 
frames = [flip_ashe28704, flip_ashe28715, flip_ashe28732, flip_ashe28801, flip_ashe28803, flip_ashe28804, flip_ashe28805, flip_ashe28806]
complete_asheville_df = pd.concat(frames, axis=1)

asheville_df = complete_asheville_df.transpose()
asheville_df.sort_values(by=['rating_score']).drop(labels="district", axis=1)

asheville_df.describe()

,district,rating_score,accuracry_review,cleanliness_review,checkin_review,communication_review,location_review,value_score,number_properties
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000
mean,28771.250000,4.892475,4.920888,4.892386,4.967363,4.952676,4.881307,4.835059,128.50000
std,45.574899,0.019263,0.016654,0.027520,0.008450,0.007041,0.032925,0.027738,98.21987
min,28704.000000,4.867083,4.896182,4.840000,4.949488,4.941250,4.819167,4.801767,24.00000
25%,28727.750000,4.879133,4.907228,4.877665,4.966366,4.949129,4.867340,4.813869,47.25000
50%,28802.000000,4.889590,4.921902,4.896848,4.968488,4.955949,4.883758,4.833079,119.00000
75%,28804.250000,4.905925,4.933507,4.908737,4.970229,4.956900,4.898840,4.851540,181.25000
max,28806.000000,4.923434,4.943636,4.929293,4.979583,4.959192,4.923939,4.874583,302.00000

In [302]:
# Start to explore correlations within the data for Asheville "reviews_scores_rating" for total rating - correlation
correlations_ashe=ashe_rows.corr()
correlations_ashe=correlations_ashe["review_scores_rating"].sort_values(ascending=False)
features=correlations_ashe.index[1:6]
correlations_ashe

review_scores_rating                            1.000000
review_scores_accuracy                          0.806759
review_scores_value                             0.735744
review_scores_cleanliness                       0.733921
review_scores_communication                     0.670030
review_scores_location                          0.520559
review_scores_checkin                           0.495233
number_of_reviews_l30d                          0.131060
reviews_per_month                               0.121143
id                                              0.093053
number_of_reviews_ltm                           0.092185
longitude                                       0.057827
neighbourhood_cleansed                          0.038637
number_of_reviews                               0.009101
host_id                                        -0.009092
latitude                                       -0.009836
minimum_nights                                 -0.031957
beds                                           -0.043317
accommodates                                   -0.066471
calculated_host_listings_count_private_rooms   -0.084409
maximum_nights                                 -0.094776
bedrooms                                       -0.099641
calculated_host_listings_count_shared_rooms    -0.119143
calculated_host_listings_count_entire_homes    -0.189796
calculated_host_listings_count                 -0.207435
host_total_listings_count                      -0.220193
host_listings_count                            -0.220193
Name: review_scores_rating, dtype: float64

In [304]:
# Explore correlation in host listing count versus other characteristics in the Asheville data
correlations_ashe_host=ashe_rows.corr()
correlations_ashe_host=correlations_ashe_host["host_listings_count"].sort_values(ascending=False)
features=correlations_ashe_host.index[1:6]
correlations_ashe_host

host_listings_count                             1.000000
host_total_listings_count                       1.000000
calculated_host_listings_count_entire_homes     0.577757
calculated_host_listings_count                  0.573715
bedrooms                                        0.221261
accommodates                                    0.195412
maximum_nights                                  0.178329
beds                                            0.170397
id                                              0.151507
longitude                                       0.119805
host_id                                         0.102246
calculated_host_listings_count_shared_rooms    -0.006564
minimum_nights                                 -0.037098
calculated_host_listings_count_private_rooms   -0.057971
latitude                                       -0.116586
number_of_reviews_l30d                         -0.121069
number_of_reviews_ltm                          -0.126769
review_scores_checkin                          -0.143637
review_scores_cleanliness                      -0.147681
number_of_reviews                              -0.151744
review_scores_location                         -0.154305
reviews_per_month                              -0.162258
neighbourhood_cleansed                         -0.191542
review_scores_accuracy                         -0.206078
review_scores_rating                           -0.220193
review_scores_value                            -0.245432
review_scores_communication                    -0.279527
Name: host_listings_count, dtype: float64

In [305]:
# Does the description accuracy of the listing correlate with a higher rating in any category for the Asheville data?
correlations_ashe_accuracy=ashe_rows.corr()
correlations_ashe_accuracy=correlations_ashe_accuracy["review_scores_accuracy"].sort_values(ascending=False)
features=correlations_ashe_accuracy.index[1:6]
correlations_ashe_accuracy

review_scores_accuracy                          1.000000
review_scores_rating                            0.806759
review_scores_value                             0.680326
review_scores_communication                     0.638231
review_scores_cleanliness                       0.636593
review_scores_checkin                           0.493106
review_scores_location                          0.401059
reviews_per_month                               0.152457
number_of_reviews_l30d                          0.142821
number_of_reviews_ltm                           0.119114
number_of_reviews                               0.078149
longitude                                       0.061237
neighbourhood_cleansed                          0.052142
id                                              0.019602
latitude                                       -0.004631
calculated_host_listings_count_private_rooms   -0.031316
host_id                                        -0.049867
minimum_nights                                 -0.062802
maximum_nights                                 -0.078413
calculated_host_listings_count_shared_rooms    -0.087392
beds                                           -0.089998
accommodates                                   -0.109392
bedrooms                                       -0.143388
host_total_listings_count                      -0.206078
host_listings_count                            -0.206078
calculated_host_listings_count_entire_homes    -0.235132
calculated_host_listings_count                 -0.244195
Name: review_scores_accuracy, dtype: float64

Does the host response rate correlate with higher overall ratings?

In [326]:
# Nashville ratings v. host response 
nash_clean2 = nash_rows.rename(columns={"neighbourhood_cleansed": "district","review_scores_accuracy":"accuracry_review", "review_scores_cleanliness":"cleanliness_review","review_scores_checkin":"checkin_review",\
    "review_scores_communication":"communication_review","review_scores_location":"location_review","review_scores_value":"value_score", "review_scores_rating": "rating_score"})

# reordering the columns 
new_column_order = ["district","host_response_rate", "rating_score"]

nash_clean2 = nash_clean2[new_column_order]
nash_host_ratings_df = nash_clean2.sort_values(by=["host_response_rate"])

In [331]:
nash_host_ratings_df

         district host_response_rate  rating_score
85    District 21                 0%          4.71
2222   District 6                 0%          4.42
852   District 19                 0%          4.78
433    District 5                 0%          4.31
877   District 19                 0%          4.76
...           ...                ...           ...
4933  District 19                99%          4.88
4930  District 19                99%          4.57
3732  District 17                99%          4.69
3308  District 18                99%          5.00
1900   District 5                99%          5.00

[2692 rows x 3 columns]

In [351]:
nash_host_ratings_df['host_response_rate'] = nash_host_ratings_df['host_response_rate'].astype('float')*100

In [352]:
nash_host_ratings_df

         district  host_response_rate  rating_score
85    District 21                0.00          4.71
2222   District 6                0.00          4.42
852   District 19                0.00          4.78
433    District 5                0.00          4.31
877   District 19                0.00          4.76
...           ...                 ...           ...
4933  District 19                0.99          4.88
4930  District 19                0.99          4.57
3732  District 17                0.99          4.69
3308  District 18                0.99          5.00
1900   District 5                0.99          5.00

[2692 rows x 3 columns]

In [353]:
nash_host_ratings_df["host_response_rate"].value_counts()

1.00    2201
0.99     216
0.98      64
0.97      48
0.90      33
0.96      28
0.91      21
0.95      13
0.94       9
0.88       8
0.93       8
0.00       7
0.67       6
0.89       5
0.80       5
0.86       5
0.50       4
0.82       3
0.75       2
0.92       2
0.73       1
0.83       1
0.60       1
0.58       1
Name: host_response_rate, dtype: int64

In [344]:
# Creating bins for different hosting_response_rate percentage 
percentage_bins = [0.0, .25, .50, .]
bin_labels = ["0-25%", "26-50%", "51-75%, 78-100%"]

nash_host_ratings_df["host_response_group"] = pd.cut(nash_host_ratings_df['host_response_rate'], percentage_bins, labels=bin_labels)

TypeError: '<' not supported between instances of 'float' and 'str'